---
name: Catalyst-Plugin-RequireSSL
version: 0.06
author:
  - 'Andy Grundman, <andy@hybridized.org>'
abstract: Force SSL mode on select pages
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.23
provides:
  Catalyst::Plugin::RequireSSL:
    file: lib/Catalyst/Plugin/RequireSSL.pm
    version: 0.06
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
