---
name: Catalyst-Plugin-RequireSSL
version: 0.03
author:
  - 'Andy Grundman, <andy@hybridized.org>'
abstract: Force SSL mode on select pages
license: perl
requires:
  Catalyst: 5.23
provides:
  Catalyst::Plugin::RequireSSL:
    file: lib/Catalyst/Plugin/RequireSSL.pm
    version: 0.03
generated_by: Module::Build version 0.2611
